# Generated by Django 2.2.1 on 2019-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(blank=True, null=True, upload_to='audioFiles/')),
                ('textfile', models.FileField(blank=True, null=True, upload_to='textFiles/')),
                ('imagefile', models.FileField(blank=True, null=True, upload_to='imageFiles/')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
